DROP PROCEDURE IF EXISTS CHECK_FOR_DUPLICATE_USER;
DROP PROCEDURE IF EXISTS ADD_NEW_USER;
DROP PROCEDURE IF EXISTS LOGIN_VERIFICATION;
DROP PROCEDURE IF EXISTS INSERT_NEW_PRODUCT;
DROP PROCEDURE IF EXISTS ADD_TO_CART;
DROP PROCEDURE IF EXISTS GET_CART;
DROP FUNCTION IF EXISTS MAP_USERNAME_TO_ID;
DROP PROCEDURE IF EXISTS PLACE_ORDER;
DROP PROCEDURE IF EXISTS BUY_NOW;
DROP TRIGGER IF EXISTS UPDATE_BUYS_ORDER;
DROP TRIGGER IF EXISTS CHECK_SHIPDATE;

DROP TABLE IF EXISTS SHIPMENT;
DROP TABLE IF EXISTS WAREHOUSE;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS TRADER;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PERSON;

exit
